version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfoliom
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:placeholder-key
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: portfoliom
      DB_USERNAME: postgres
      DB_PASSWORD: Hachi3334*

  db:
    image: postgres:16
    container_name: portfoliom_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: portfoliom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hachi3334*
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
